name: GitHub Issue to JSON
description: Convert GitHub issues to JSON data files.
runs:
  using: node16
  main: issue-to-json.js

inputs:
  folder:
    description: The target output directory for the JSON data file.
    default: _data/
  issue-template:
    description: The YAML file for the GitHub issue form template
    required: true
  hash-property-name:
    description: The object property to use to generate the has for the file name.
    required: true
